export default [
  { _id: 'ethereum@arbitrum' },
  { _id: 'avalanche@avalanche-c-chain' },
  { _id: 'ethereum@base' },
  { _id: 'binance-coin@binance-smart-chain' },
  { _id: 'bitcoin@bitcoin' },
  { _id: 'bitcoin-cash@bitcoin-cash' },
  { _id: 'cardano@cardano' },
  { _id: 'dash@dash' },
  { _id: 'dogecoin@dogecoin' },
  { _id: 'eos@eos' },
  { _id: 'ethereum@ethereum' },
  { _id: 'ethereum-classic@ethereum-classic' },
  { _id: 'litecoin@litecoin' },
  { _id: 'monero@monero' },
  { _id: 'ethereum@optimism' },
  { _id: 'polygon@polygon' },
  { _id: 'solana@solana' },
  { _id: 'sonic@sonic' },
  { _id: 'stellar@stellar' },
  { _id: 'sui@sui' },
  { _id: 'tether@ethereum' },
  { _id: 'toncoin@toncoin' },
  { _id: 'tron@tron' },
  { _id: 'xrp@ripple' },
];
