steps:

- name: 'node:20.11.1'
  id: 'build web'
  env:
    - 'VITE_DISTRIBUTION=${_VITE_DISTRIBUTION}'
    - 'VITE_COMMIT=${COMMIT_SHA}'
    - 'VITE_SITE_URL=${_VITE_SITE_URL}'
    - 'VITE_SITE_URL_TOR=${_VITE_SITE_URL_TOR}'
    - 'VITE_API_HOST=${_VITE_API_HOST}'
    - 'VITE_API_HOST_TOR=${_VITE_API_HOST_TOR}'
    - 'VITE_SENTRY_DSN=${_VITE_SENTRY_DSN}'
    - 'VITE_SENTRY_DSN_TOR=${_VITE_SENTRY_DSN_TOR}'
    - 'VITE_SENTRY_ENVIRONMENT=${_VITE_SENTRY_ENVIRONMENT}'
    - 'VITE_CHANGELLY_REF=${_VITE_CHANGELLY_REF}'
    - 'VITE_MOONPAY_API_KEY=${_VITE_MOONPAY_API_KEY}'
    - 'VITE_WALLETCONNECT_ID=${_VITE_WALLETCONNECT_ID}'
    - 'VITE_DUMMY_ACCOUNT=${_VITE_DUMMY_ACCOUNT}'
    - 'BASE_URL=${_BASE_URL}'
    - 'SENTRY_ORG=${_SENTRY_ORG}'
    - 'SENTRY_PROJECT=${_SENTRY_PROJECT}'
    - 'SENTRY_AUTH_TOKEN=${_SENTRY_AUTH_TOKEN}'
    - 'NODE_OPTIONS="--max-old-space-size=3575"'
  dir: web
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      npm config set @coinspace:registry https://npm.pkg.github.com \
      && npm config set "//npm.pkg.github.com/:_authToken" ${_NPM_READ_TOKEN} \
      && npm ci \
      && npm run i18n:ci \
      && npm run lint \
      && npm run lint:style \
      && npm run build

- name: 'gcr.io/cloud-builders/docker'
  id: 'build server'
  dir: server
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      docker build --build-arg NODE_AUTH_TOKEN=${_NPM_READ_TOKEN} --tag "gcr.io/$PROJECT_ID/${_NAMESPACE}/${_APP}:latest" . \
      && docker push "gcr.io/$PROJECT_ID/${_NAMESPACE}/${_APP}:latest"

- name: 'gcr.io/cloud-builders/kubectl'
  id: 'deploy'
  args: ['delete', 'po', '-l', 'app=${_APP}', '--namespace', '${_NAMESPACE}']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'purge cdn'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    if [[ -n "${_CDN_URL_MAP_NAME}" ]]; then
      gcloud compute url-maps invalidate-cdn-cache ${_CDN_URL_MAP_NAME} --host ${_CDN_HOST} --path "/*" --async
    fi

timeout: 900s
