export default [{
  _id: 'bitcoin-cash@bitcoin-cash',
  scheme: 'bitcoincash',
}, {
  _id: 'bitcoin@bitcoin',
  scheme: 'bitcoin',
}, {
  _id: 'cardano@cardano',
  scheme: 'cardano',
}, {
  _id: 'dash@dash',
  scheme: 'dash',
}, {
  _id: 'dogecoin@dogecoin',
  scheme: 'dogecoin',
}, {
  _id: 'eos@eos',
  scheme: 'eos',
}, {
  _id: 'ethereum@ethereum',
  scheme: 'ethereum',
}, {
  _id: 'litecoin@litecoin',
  scheme: 'litecoin',
}, {
  _id: 'monero@monero',
  scheme: 'monero',
}, {
  _id: 'stellar@stellar',
  scheme: 'stellar',
}, {
  _id: 'xrp@ripple',
  scheme: 'ripple',
}];
